import tarkhineh from "./assets/image/tarkhineh.webp";
import moboShare from "./assets/image/moboShare.webp";
import mrAghrabeh from "./assets/image/mrAghrabeh.webp";
import dataFinance from "./assets/image/dataFinance.webp";

export const myProjects = [
  {
    id: 0,
    lang: "en",
    name: "tarkhineh",
    title: "Chain restaurant management website",
    imageUrl: tarkhineh,
    imageGallery: [],
    describtion: [
      {
        id: 0,
        title: "",
      },
    ],
    quickDescribtion: "",
    technolegies: [],
    githubUrl: "https://github.com/dev-hosein-moradi/tarkhineh-food",
    liveDemoUrl: "https://tarkhineh-food.vercel.app/",
    status: "in development",
    statusCode: 0,
  },
  {
    id: 1,
    lang: "fa",
    name: "",
    imageUrl: tarkhineh,
    imageGallery: [],
    describtion: [],
    quickDescribtion: "",
    technolegies: [],
    githubUrl: "",
    liveDemoUrl: "",
  },
  {
    id: 2,
    lang: "en",
    name: "moboShare",
    title: "social media platform",
    imageUrl: moboShare,
    imageGallery: [],
    describtion: [],
    quickDescribtion: "",
    technolegies: [],
    githubUrl: "https://github.com/dev-hosein-moradi/moboshare",
    liveDemoUrl: "https://moboshare.vercel.app/",
    status: "Down for update new version",
    statusCode: -1,
  },
  {
    id: 3,
    lang: "fa",
    name: "",
    imageUrl: tarkhineh,
    imageGallery: [],
    describtion: [],
    quickDescribtion: "",
    technolegies: [],
    githubUrl: "",
    liveDemoUrl: "",
  },
  {
    id: 4,
    lang: "en",
    name: "mr aghrabeh",
    title: "shopify web site for wrist and wall watch",
    imageUrl: mrAghrabeh,
    imageGallery: [],
    describtion: [],
    quickDescribtion: "",
    technolegies: [],
    githubUrl: "https://github.com/dev-hosein-moradi/mr-aghrabeh",
    liveDemoUrl: "https://mr-aghrabeh.vercel.app/",
    status: "Completed",
    statusCode: 1,
  },
  {
    id: 5,
    lang: "fa",
    name: "",
    imageUrl: tarkhineh,
    imageGallery: [],
    describtion: [],
    quickDescribtion: "",
    technolegies: [],
    githubUrl: "",
    liveDemoUrl: "",
  },
  {
    id: 6,
    lang: "en",
    name: "finance",
    title: "Data finance platform",
    imageUrl: dataFinance,
    imageGallery: [],
    describtion: [],
    quickDescribtion: "",
    technolegies: [],
    githubUrl: "https://github.com/dev-hosein-moradi/data-finance",
    liveDemoUrl: "https://data-finance-psi.vercel.app/",
    status: "Completed",
    statusCode: 1,
  },
  {
    id: 7,
    lang: "fa",
    name: "",
    imageUrl: tarkhineh,
    imageGallery: [],
    describtion: [],
    quickDescribtion: "",
    technolegies: [],
    githubUrl: "",
    liveDemoUrl: "",
  },
];
